task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 13 # your dataset classes
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /home/naiben/WNB_Visual_Studio_Code/VSCode_Projects/Datasets/disease_l_coco/images/train
    ann_file: /home/naiben/WNB_Visual_Studio_Code/VSCode_Projects/Datasets/disease_l_coco/annotations/train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /home/naiben/WNB_Visual_Studio_Code/VSCode_Projects/Datasets/disease_l_coco/images/test
    ann_file: /home/naiben/WNB_Visual_Studio_Code/VSCode_Projects/Datasets/disease_l_coco/annotations/test.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
